const fs = require('fs');
const path = require('path');

const dir = path.join('/Users/efekarakoyun/hukukçalışma/uygulama/frontend/data/practice_cases');

function appendCases(filename, newCases) {
  const filePath = path.join(dir, filename);
  let data = [];
  if (fs.existsSync(filePath)) {
    try { data = JSON.parse(fs.readFileSync(filePath, 'utf-8')); } catch(e) {}
  }
  let startIdx = data.length + 900; 
  newCases.forEach((c, idx) => {
    c.id = `${c.course}_AUHF_BULK1_${startIdx + idx}`;
    data.unshift(c); 
  });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

const cases = {
  "ceza_muhakemesi": [
    { course: "ceza_muhakemesi", title: "CMK - İletişimin Tespiti ve Dinlenmesi", difficulty: "zor", scenario: "Uyuşturucu ticareti şüphesiyle soruşturulan (A)'nın telefonu savcı kararıyla dinlenmeye başlanır. Dinleme kararından 48 saat sonra hakim onayı alınır. (A)'nın avukatı dinleme kayıtlarının hukuka aykırı olduğunu iddia eder. Hukuki durumu açıklayınız.", ideal_solution: "CMK m.135 gereği iletişimin tespiti ve dinlenmesi hakim kararıyla, gecikmesinde sakınca bulunan hallerde savcı kararıyla olur. Savcı kararı derhal hakime sunulur ve hakim 24 saat içinde kararını verir. Olayda 48 saat sonra hakim onayı alınmıştır, bu nedenle dinleme hukuka aykırı hale gelmiştir ve delil olarak kullanılamaz.", key_points: ["İletişimin dinlenmesi", "Savcı kararı", "24 saat içinde hakim onayı", "Hukuka aykırı delil"], topics: ["Koruma Tedbirleri", "Telekomünikasyon Yoluyla İletişimin Denetlenmesi"] },
    { course: "ceza_muhakemesi", title: "CMK - Zorunlu Müdafilik", difficulty: "orta", scenario: "16 yaşındaki (Ç), hırsızlık şüphesiyle gözaltına alınır. Karakolda avukat istemediğini söyler ve ifadesi alınır. Bu ifade mahkemede delil olarak kullanılabilir mi?", ideal_solution: "CMK m.150/2 uyarınca, şüpheli veya sanık 18 yaşını doldurmamışsa, istemi aranmaksızın bir müdafi görevlendirilir (zorunlu müdafilik). (Ç)'nin avukat istemediğini beyan etmesi hukuken geçersizdir. Müdafi bulunmaksızın alman ifade, hakim veya mahkeme huzurunda şüpheli tarafından doğrulanmadıkça delil olarak kullanılamaz (CMK m.148/4).", key_points: ["Zorunlu müdafi", "18 yaşından küçükler", "CMK m.150/2", "İfadenin delil değeri"], topics: ["Soruşturma Evresi", "Müdafi"] },
    { course: "ceza_muhakemesi", title: "CMK - Gözaltı Süreleri", difficulty: "kolay", scenario: "Terör örgütü üyeliği (toplu suç) şüphesiyle yakalanan (T), 5 gün boyunca karakolda gözaltında tutulur. Bu süre yasal mıdır?", ideal_solution: "Toplu suçlarda gözaltı süresi, delillerin toplanmasındaki güçlük veya şüpheli sayısının çokluğu nedeniyle savcı kararıyla 4 günü geçemez (CMK m.91/3). Olayda 5 gün gözaltında tutulması açıkça hukuka aykırıdır. Şüpheli derhal hakime çıkarılmalıydı.", key_points: ["Gözaltı süresi", "Toplu suçlar", "Maksimum 4 gün"], topics: ["Koruma Tedbirleri", "Gözaltı"] },
    { course: "ceza_muhakemesi", title: "CMK - Çapraz Sorgu", difficulty: "zor", scenario: "Duruşmada tanık olarak dinlenen (X)'e, sanık avukatı doğrudan soru sormak ister ancak mahkeme başkanı 'Sorularınızı bana yöneltin, ben uygun bulursam sorarım' diyerek müdahale eder. Avukat bu duruma itiraz eder. Kim haklıdır?", ideal_solution: "CMK m.201 uyarınca 'Doğrudan Soru Yöneltme' (Çapraz sorgu) hakkı vardır. Sanık avukatı (müdafi), tanığa doğrudan soru yöneltebilir. Mahkeme başkanının araya girip soruyu kendi üzerinden sorması usule aykırıdır. Avukat itirazında haklıdır.", key_points: ["Doğrudan soru yöneltme", "Çapraz sorgu", "CMK m.201"], topics: ["Kovuşturma Evresi", "Duruşma"] },
    { course: "ceza_muhakemesi", title: "CMK - İddianamenin İadesi Süresi", difficulty: "orta", scenario: "Savcılık iddianameyi mahkemeye sunduktan 20 gün sonra mahkeme, suçun vasfının yanlış belirtildiği gerekçesiyle iddianameyi iade eder. Savcı bu iade kararına itiraz eder. İtirazın sonucu ne olmalıdır?", ideal_solution: "CMK m.174 gereğince mahkeme, iddianamenin iadesine 15 gün içinde karar vermelidir. 15 gün geçtikten sonra iddianame iade edilemez, kabul edilmiş sayılır. Mahkemenin 20. günde iade etmesi usule aykırıdır. Savcının itirazı kabul edilmelidir.", key_points: ["İddianamenin iadesi", "15 günlük süre", "CMK m.174"], topics: ["Kovuşturma Evresi", "İddianame"] },
    { course: "ceza_muhakemesi", title: "CMK - Adli Kontrol ve Kefalet", difficulty: "zor", scenario: "Tutuklama istemiyle hakimliğe sevk edilen (A) hakkında hakim, tutuklama yerine '100.000 TL kefalet ödemesi' şartıyla adli kontrol kararı verir. (A) parayı ödeyemez. Hakim bu durumda ne kararı vermelidir?", ideal_solution: "CMK m.109/2-f uyarınca adli kontrol yükümlülükleri arasında 'güvence parası yatırmak' (kefalet) vardır. Şüpheli güvence parasını ödeyemiyorsa veya adli kontrol şartlarına uymuyorsa, hakim adli kontrol kararını kaldırarak şüphelinin tutuklanmasına karar verebilir (CMK m.112).", key_points: ["Adli kontrol", "Güvence parası (Kefalet)", "Tutuklamaya çevirme", "CMK m.112"], topics: ["Koruma Tedbirleri", "Adli Kontrol"] },
    { course: "ceza_muhakemesi", title: "CMK - Görevsizlik Kararı", difficulty: "orta", scenario: "Asliye Ceza Mahkemesinde görülmekte olan bir davada, mahkeme sanığın eyleminin 'Yağma' suçunu oluşturabileceğini değerlendirir ve görevsizlik kararı vererek dosyayı Ağır Ceza Mahkemesine gönderir. Ağır Ceza Mahkemesi, eylemin 'Hırsızlık' olduğu gerekçesiyle karşı görevsizlik kararı verebilir mi?", ideal_solution: "CMK m.5'e göre alt dereceli mahkemenin verdiği görevsizlik kararı üst dereceli mahkemeyi bağlar. Asliye Ceza Mahkemesinin görevsizlik kararı üzerine Ağır Ceza Mahkemesi bu kararla bağlıdır ve yargılamayı yapmak zorundadır, karşı görevsizlik kararı veremez.", key_points: ["Görevsizlik", "Alt mahkemenin kararının bağlayıcılığı", "CMK m.5"], topics: ["Görev ve Yetki"] },
    { course: "ceza_muhakemesi", title: "CMK - Kanun Yararına Bozma", difficulty: "zor", scenario: "Yerel mahkeme (S) hakkında basit yaralama suçundan beraat kararı verir ve karar istinaf/temyiz edilmeksizin kesinleşir. Aylar sonra, kararın açıkça hukuka aykırı olduğu ve delillerin hiçe sayıldığı fark edilir. Adalet Bakanlığı bu kararı nasıl bozabilir?", ideal_solution: "İstinaf veya temyiz incelemesinden geçmeksizin kesinleşen mahkeme kararlarındaki hukuka aykırılıklar için Adalet Bakanlığı, Yargıtay Cumhuriyet Başsavcılığından 'Kanun Yararına Bozma' (CMK m.309) talebinde bulunur. Başsavcı bu talebi Yargıtay'a götürür ve Yargıtay ilgili ceza dairesi kararı kanun yararına bozar.", key_points: ["Olağanüstü kanun yolu", "Kanun yararına bozma", "CMK m.309", "Adalet Bakanlığı"], topics: ["Kanun Yolları", "Olağanüstü Kanun Yolları"] },
    { course: "ceza_muhakemesi", title: "CMK - HAGB (Hükmün Açıklanmasının Geri Bırakılması)", difficulty: "kolay", scenario: "Sanık (Y) hakkında 3 yıl hapis cezası verilir ve sanık daha önce sabıkasız olduğu için HAGB uygulanır. Bu karar hukuka uygun mudur?", ideal_solution: "CMK m.231'e göre HAGB kararı verilebilmesi için kurulan mahkumiyet hükmünün '2 yıl veya daha az süreli hapis veya adli para cezası' olması gerekir. Olayda 3 yıl hapis cezası verildiği için HAGB uygulanamaz. Karar hukuka aykırıdır.", key_points: ["HAGB şartları", "2 yıl sımırı", "CMK m.231"], topics: ["Kovuşturma Evresi", "Hüküm"] },
    { course: "ceza_muhakemesi", title: "CMK - Şikayetten Vazgeçme", difficulty: "orta", scenario: "Hakaret suçu (şikayete tabi) sebebiyle sanık (S) yargılanırken, müşteki (M) şikayetinden vazgeçtiğini bildirir. Ancak (S), 'Ben bu suçu işlemedim, beraat etmek istiyorum, şikayetten vazgeçmeyi kabul etmiyorum' der. Mahkeme nasıl karar vermelidir?", ideal_solution: "TCK m.73/6 gereğince, şikayetten vazgeçme, onu kabul etmeyen sanığı etkilemez. Sanık (S) beraat etmek istiyor ve şikayetten vazgeçmeyi kabul etmiyorsa, mahkeme yargılamaya devam etmeli ve sanığın beraat edip etmeyeceğine karar vermelidir. Doğrudan düşme kararı verilemez.", key_points: ["Şikayetten vazgeçme", "Sanığın kabulü şartı", "Düşme kararı"], topics: ["Muhakeme Şartları", "Şikayet"] }
  ],
  "deniz_ticareti": [
    { course: "deniz_ticareti", title: "Deniz Ticareti - Çatma (Collision)", difficulty: "zor", scenario: "Kusursuz iki gemi, İstanbul Boğazı'nda yoğun sis nedeniyle çarpışır (çatma). Her iki gemide de hasar oluşur. A gemisi B gemisinden zararının tazminini isteyebilir mi?", ideal_solution: "TTK m.1228 uyarınca, çatma umulmayan bir hal veya mücbir sebepten ileri gelmişse veya neden ileri geldiği anlaşılamıyorsa (kusursuz çatma), zarara uğrayanlar kendi zararlarına katlanırlar. Kimse diğerinden tazminat isteyemez. Olayda yoğun sis ve kusursuzluk (mücbir sebep) durumu olduğundan her gemi kendi zararına katlanacaktır.", key_points: ["Kusursuz çatma", "Mücbir sebep", "TTK m.1228"], topics: ["Deniz Kazaları", "Çatma"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Müşterek Avarya İştirak", difficulty: "orta", scenario: "Gemi batma tehlikesi yaşarken kaptan 10 ton çimentoyu denize atar (müşterek avarya). Ancak gemi kurtulamaz ve fırtınanın etkisiyle kayalıklara çarparak tamamen batar. Çimento sahibi, gemi malikinden müşterek avarya payı isteyebilir mi?", ideal_solution: "Müşterek avarya alacağının doğması için yapılan fedakarlığın 'faydalı bir sonuç' doğurması, yani geminin ve diğer yüklerin kurtulması şarttır (York-Anvers Kuralları / TTK m.1272). Olayda gemi tamamen battığı ve hiçbir değer kurtulamadığı için faydalı sonuç şartı gerçekleşmemiştir. Çimento sahibi müşterek avarya iştirak payı isteyemez.", key_points: ["Müşterek avarya", "Faydalı sonuç şartı", "Geminin batması"], topics: ["Deniz Kazaları", "Müşterek Avarya"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Konişmento (Bill of Lading)", difficulty: "orta", scenario: "Yükleten (Y), 1000 koli pamuğu taşıyan (T)'ye teslim etmiş ve 'Emre Yazılı Konişmento' almıştır. (Y), konişmentoyu ciro ederek bankaya (B) devreder. Gemi varış limanına geldiğinde (T), yükü konişmentoyu ibraz edemeyen alıcı (A)'ya teslim eder. Banka (B), (T)'ye dava açar. Sonuç ne olur?", ideal_solution: "Konişmento, eşyayı temsil eden bir kıymetli evraktır. Taşıyan (T), yükü ancak konişmentonun asıl nüshasını kendisine ibraz eden meşru hamile teslim edebilir (TTK m.1228). Konişmentoyu ibraz edemeyen (A)'ya yükü teslim eden (T), meşru hamil olan Banka (B)'ye karşı zarardan (yükün bedelinden) sorumludur.", key_points: ["Konişmento", "Eşyayı temsil edici nitelik", "Meşru hamile teslim"], topics: ["Taşıma Sözleşmeleri", "Konişmento"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Gemi Sicili", difficulty: "kolay", scenario: "15 grostonluk ticari bir gemi maliki olan (M), gemisini Türk Gemi Siciline tescil ettirmek istemektedir. Sicil memuru, geminin 18 grostondan küçük olduğu gerekçesiyle tescili reddeder. Memurun işlemi hukuka uygun mudur?", ideal_solution: "TTK m.955'e göre, 18 groston (GT) ve daha büyük ticari gemilerin tescili mecburidir. Ancak 18 GT'den küçük ticari gemilerin tescili malikin İHTİYARINA (isteğine) bırakılmıştır. Yani (M) talep ederse sicil memuru bunu tescil etmek ZORUNDADIR. Memurun reddi hukuka aykırıdır.", key_points: ["Gemi sicili", "18 GT kuralı", "İhtiyari tescil"], topics: ["Gemi Sicili"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Kaptanın Yetkileri", difficulty: "zor", scenario: "Gemi denizin ortasında arızalanır ve erzakları tükenir. Kaptan (K), gemiyi en yakın limana çektirmek ve mürettebata erzak almak için gemi donatanına (D) ulaşamaz. Kaptan, geminin yükünün bir kısmını (Y firmasına ait kahveleri) o limandaki bir tüccara satarak para bulur. Y firması bu satışın yetkisiz olduğunu iddia eder.", ideal_solution: "TTK m.1089 uyarınca Kaptan, yolculuk sırasında geminin korunması veya yolculuğun tamamlanması için acil para ihtiyacı doğarsa ve donatana ulaşılamıyorsa, öncelikle gemiyi veya yükü rehin edebilir, bu mümkün değilse en son çare olarak yükü SATABİLİR. Olayda donatana ulaşılamadığı ve acil erzak/tamir ihtiyacı olduğu için kaptanın yükü satma yetkisi yasal olarak doğmuştur. Y firmasının itirazı haksızdır, zararını donatandan talep etmelidir.", key_points: ["Kaptanın yasal yetkileri", "Yükün satılması (Acil durum)", "TTK m.1089"], topics: ["Gemi Adamları", "Kaptan"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Gemi Alacaklısı Hakkı", difficulty: "orta", scenario: "Gemide çalışan gemi adamı (G), 3 aylık maaşını alamadığı için gemiye karşı 'Gemi Alacaklısı Hakkı' (Maritime Lien) iddia ederek gemiyi haczettirmek ister. Geminin mülkiyeti ise bir hafta önce (X)'e satılmıştır. (X), kendisinin borcu olmadığını ileri sürer.", ideal_solution: "TTK m.1320'ye göre gemi adamlarının ücret alacakları, kanundan doğan bir 'Gemi Alacaklısı Hakkı'dır. Bu hak, gemiyi takip eder (Ayni bir haktır). Geminin mülkiyeti kime devredilirse devredilsin, gemi alacaklısı hakkı gemi üzerinde varlığını sürdürür. (G), yeni malik (X)'e karşı da geminin haczini ve satışını isteyebilir.", key_points: ["Gemi alacaklısı hakkı", "Gizli rehin (Maritime Lien)", "Takip hakkı"], topics: ["Ayni Haklar", "Gemi Alacaklısı Hakkı"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Zaman Çarteri (Time Charter)", difficulty: "zor", scenario: "Zaman çarteri sözleşmesiyle bir gemiyi kiralayan tahsis alan (T), gemiyi ticari olarak kendi emir ve talimatlarına göre işletmektedir. Gemi, (T)'nin talimatıyla tehlikeli bir limana girerken karaya oturur. Hasardan kim sorumludur?", ideal_solution: "Zaman çarteri sözleşmesinde (TTK m.1131), tahsis eden (malik) geminin teknik idaresinden, tahsis alan (T) ise geminin TİCARİ idaresinden sorumludur. Kaptan, ticari konularda (T)'nin emirlerine uymak zorundadır. Tehlikeli (emniyetsiz) bir limana girme talimatı ticari bir emir olup, bu emrin yerine getirilmesi sırasında doğan zarardan kural olarak Tahsis Alan (T) sorumludur.", key_points: ["Zaman çarteri", "Ticari idare - Teknik idare", "Güvenli liman şartı"], topics: ["Gemi Kiralama", "Zaman Çarteri"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Kurtarma ve Yardım", difficulty: "orta", scenario: "Açık denizde sürüklenen (S) gemisine, oradan geçmekte olan (K) gemisi gönüllü olarak halat atıp onu limana çeker. (K), kurtarma ücreti talep eder. (S)'nin maliki ise 'Biz sizden yardım istemedik' diyerek ödemeyi reddeder.", ideal_solution: "TTK m.1299 vd. (1989 Kurtarma Sözleşmesi) uyarınca, kurtarma ücreti talep edebilmek için kurtarma eyleminin 'faydalı bir sonuç' doğurması yeterlidir (No cure no pay ilkesi). Kurtarılanın açık ve makul bir itirazı olmadığı sürece, gönüllü yapılan faydalı kurtarma operasyonları ücrete hak kazandırır. (K) gemisi kurtarma ücreti alabilir.", key_points: ["Kurtarma ve yardım", "Faydalı sonuç (No cure no pay)", "Açık itiraz yokluğu"], topics: ["Deniz Kazaları", "Kurtarma"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Navlun Sözleşmesinde Yükleme Süresi (Starya)", difficulty: "kolay", scenario: "Gemi yükleme için limana gelir ve 'Hazırlık İhbarnamesi' verir. Starya (yükleme süresi) işlemeye başlar. Ancak liman işçilerinin grevi nedeniyle yükleme 3 gün durur. Taşıyan, bu 3 gün için sürastarya (demurrage) ücreti ister.", ideal_solution: "TTK m.1154 uyarınca, starya süresi içinde ortaya çıkan ve taşıtanın şahsına bağlı olmayan (mücbir sebep niteliğindeki grev vb.) engeller starya süresinin işlemesini durdurur. Dolayısıyla grevde geçen 3 gün starya süresinden sayılmaz ve taşıyan bu günler için sürastarya ücreti isteyemez.", key_points: ["Starya (Yükleme süresi)", "Sürastarya", "Mücbir sebep (Grev)"], topics: ["Navlun Sözleşmesi", "Yükleme ve Boşaltma"] },
    { course: "deniz_ticareti", title: "Deniz Ticareti - Taşıyanın Sorumluluğu (Hague-Visby Kuralları)", difficulty: "zor", scenario: "Taşıyan (T), yükü sağlam olarak teslim almış ancak seyir esnasında kaptanın seyir haritalarını yanlış okuması (navigasyon hatası) nedeniyle gemi sığlığa bindirmiş ve yük zarar görmüştür. Taşıtan zararın tazminini ister. Taşıyan sorumlu mudur?", ideal_solution: "Deniz ticaretinde Hague-Visby kurallarına dayanan TTK m.1179'a göre, taşıyan, kaptanın veya gemi adamlarının 'geminin sevk ve idaresindeki' (teknik idare/navigasyon) kusurlarından dolayı yükle ilgililere karşı SORUMLU DEĞİLDİR (Teknik kusur istisnası). Haritayı yanlış okuma tipik bir teknik idare kusuru olduğundan Taşıyan (T) zarardan sorumlu tutulamaz.", key_points: ["Hague-Visby kuralları", "Teknik kusur istisnası", "Navigasyon hatası", "Sorumsuzluk hali"], topics: ["Navlun Sözleşmesi", "Taşıyanın Sorumluluğu"] }
  ],
  "is_hukuku": [
    { course: "is_hukuku", title: "İş Hukuku - İşe İade ve İşe Başlatmama Tazminatı", difficulty: "zor", scenario: "İş güvencesi kapsamında olan (İ), işten çıkarılınca işe iade davası açmış ve kazanmıştır. (İ), süresi içinde işverene başvurarak işe başlatılmasını talep etmiş, işveren (İ)'yi işe başlatmamış ve ona 4 aylık işe başlatmama tazminatını ödemiştir. Ancak işveren, ihbar ve kıdem tazminatını ödemeyi reddetmiştir. Hukuki durum nedir?", ideal_solution: "İş K. m.21'e göre, işe iade davasını kazanan işçi süresi içinde başvurmasına rağmen işveren işe başlatmazsa, işverence yapılmış olan fesih GEÇERLİ fesih haline gelir ve iş ilişkisi bu tarihte sona ermiş sayılır. Bu nedenle işveren, işe başlatmama tazminatına ek olarak (daha önce ödememişse) feshe bağlı haklar olan Kıdem ve İhbar tazminatlarını da o günkü (işe başlatmama anındaki) ücret üzerinden hesaplayarak işçiye ödemek ZORUNDADIR.", key_points: ["İşe iade davası", "İşe başlatmama tazminatı", "Feshin geçerli hale gelmesi", "Kıdem ve ihbar tazminatı ödemesi"], topics: ["İş Güvencesi", "İşe İade"] },
    { course: "is_hukuku", title: "İş Hukuku - Belirli Süreli İş Sözleşmesi", difficulty: "orta", scenario: "Bir banka, gişe görevlisi (G) ile '1 yıllık belirli süreli' iş sözleşmesi yapar. Süre bitiminde sözleşme kendiliğinden sona erer. (G), kıdem tazminatı ve işe iade davası açar.", ideal_solution: "İş K. m.11'e göre belirli süreli iş sözleşmesi ancak 'objektif koşulların' (belirli bir işin tamamlanması, kampanya dönemi vs.) varlığı halinde yapılabilir. Gişe memurluğu sürekli ve esaslı bir iştir, objektif koşul yoktur. Bu nedenle sözleşme baştan itibaren BELİRSİZ süreli sayılır. Sözleşmenin süre bitimiyle sonlandırılması 'haksız fesih' niteliğindedir. (G) 1 yıllık kıdemi doldurduğu ve bankada 30+ işçi olduğu varsayımıyla (G) işe iade davası açabilir ve kıdem tazminatı talep edebilir.", key_points: ["Belirli süreli iş sözleşmesi", "Objektif koşul şartı", "Belirsiz süreliye dönüşme", "Haksız fesih"], topics: ["İş Sözleşmesi Türleri"] },
    { course: "is_hukuku", title: "İş Hukuku - Kadın İşçinin Evlenmesi", difficulty: "kolay", scenario: "Kadın işçi (K), evlendikten 8 ay sonra iş sözleşmesini evlilik gerekçesiyle fesheder. İşveren, (K)'nın ihbar süresine uymadan işi bıraktığını belirterek kıdem tazminatını ödemez ve ihbar tazminatı ister.", ideal_solution: "1475 sayılı mülga İş K. m.14 (halen yürürlüktedir) gereğince, kadın işçi evlendiği tarihten itibaren 1 yıl içinde kendi arzusu ile iş sözleşmesini sona erdirirse KIDEM TAZMİNATINA hak kazanır. Evlilik nedeniyle fesih haklı nedene dayanmadığından işçi ihbar tazminatı alamaz ancak işveren de ondan ihbar tazminatı İSTEYEMEZ. Fesih derhal etki doğurur.", key_points: ["Kadın işçinin evlenmesi", "1 yıllık süre", "Kıdem tazminatı", "İhbar tazminatı yokluğu"], topics: ["Kıdem Tazminatı", "Fesih"] },
    { course: "is_hukuku", title: "İş Hukuku - Fazla Çalışma (Mesai)", difficulty: "orta", scenario: "Haftalık 40 saatlik sözleşmeyle çalışan (Ç), bir haftada toplam 48 saat çalıştırılmıştır. (Ç)'nin 40 saatten 48 saate kadar olan 8 saatlik çalışmasının hukuki niteliği ve ücreti nedir?", ideal_solution: "İş K. m.41'e göre haftalık normal çalışma süresi azami 45 saattir. Sözleşme ile belirlenen haftalık çalışma süresi (40 saat) ile kanuni sınır (45 saat) arasındaki 5 saatlik çalışma 'Fazla Sürelerle Çalışma'dır ve ücreti %25 zamlı ödenir. 45 saati aşan (45-48 arası) 3 saatlik çalışma ise 'Fazla Çalışma'dır ve ücreti %50 zamlı ödenir.", key_points: ["Fazla çalışma", "Fazla sürelerle çalışma", "45 saat sınırı", "%25 ve %50 zam oranı"], topics: ["Çalışma Süreleri", "Fazla Çalışma"] },
    { course: "is_hukuku", title: "İş Hukuku - İşyerinin Devri", difficulty: "zor", scenario: "(A) Tekstil, fabrikasını tüm işçileriyle birlikte (B) Tekstil'e devreder. İşçi (İ), (A) döneminde 5 yıl, (B) döneminde ise 2 yıl çalıştıktan sonra (B) tarafından haksız yere işten çıkarılır. (İ), 7 yıllık kıdem tazminatının tamamını eski işveren (A)'dan isteyebilir mi?", ideal_solution: "İş K. m.6 uyarınca işyeri devrinde iş sözleşmeleri bütün hak ve borçları ile devralana geçer. Kıdem tazminatı bakımından (İş K. m.14); işyerini devreden işveren (A), işçinin kendisinde çalıştığı süre (5 yıl) ve o zamanki ücret seviyesiyle sınırlı olarak YENİ İŞVEREN (B) ile MÜTESELSİLEN sorumludur. (İ), 7 yıllık kıdeminin tamamı için (B)'ye başvurabilirken, (A)'dan sadece ilk 5 yıla isabet eden kısmı talep edebilir.", key_points: ["İşyerinin devri", "Kıdem tazminatı müteselsil sorumluluk", "Devredenin sınırlı sorumluluğu"], topics: ["İşyeri", "İşyerinin Devri"] },
    { course: "is_hukuku", title: "İş Hukuku - Haklı Nedenle Fesih (İşçi)", difficulty: "orta", scenario: "İşçi (M)'nin maaşları son 3 aydır sürekli olarak 20 gün gecikmeli ödenmektedir. (M), bu durumu gerekçe göstererek iş sözleşmesini derhal fesheder ve kıdem tazminatını talep eder. İşveren ise 'maaşları ödüyoruz sadece geçikiyor' diyerek talebi reddeder.", ideal_solution: "İş K. m.24/II-e uyarınca, işveren tarafından işçinin ücreti kanun hükümleri veya sözleşme şartlarına uygun olarak hesaplanmaz veya ödenmezse işçi iş sözleşmesini derhal (haklı nedenle) feshedebilir. Ücretin sürekli gecikmeli ödenmesi haklı fesih nedenidir. (M) kıdem tazminatına hak kazanır ancak haklı nedenle dahi olsa kendisi feshettiği için ihbar tazminatı alamaz.", key_points: ["Ücretin ödenmemesi/gecikmesi", "İşçi lehine haklı fesih", "İş K. m.24", "Kıdem tazminatı"], topics: ["Sözleşmenin Feshi", "Haklı Nedenle Fesih"] },
    { course: "is_hukuku", title: "İş Hukuku - Geçerli Nedenle Fesih (Performans)", difficulty: "zor", scenario: "Satış temsilcisi (S), iş güvencesi kapsamındadır. Son 6 aydır satış hedeflerini tutturamamaktadır. İşveren, (S)'nin savunmasını almadan 'performans düşüklüğü' gerekçesiyle sözleşmesini geçerli nedenle (İş K. m.18) feshedip ihbar ve kıdemini öder. (S) işe iade davası açar.", ideal_solution: "İş K. m.19/2'ye göre, işveren 'işçinin performansı veya davranışından' kaynaklanan nedenlerle fesih yapacaksa, işçinin SAVUNMASINI ALMAK ZORUNDADIR. Savunma alınmadan yapılan fesih, performans düşüklüğü ispatlansa dahi sırf usul eksikliğinden (savunma alınmamasından) dolayı GEÇERSİZ sayılır. Mahkeme (S)'nin işe iadesine karar vermelidir.", key_points: ["Geçerli fesih", "Performans düşüklüğü", "Savunma alma zorunluluğu (İş K. m.19)", "Feshin geçersizliği"], topics: ["İş Güvencesi", "Geçerli Nedenle Fesih"] },
    { course: "is_hukuku", title: "İş Hukuku - Grev ve Lokavt", difficulty: "orta", scenario: "Sendika ile işveren arasında TİS görüşmeleri uyuşmazlıkla sonuçlanır. Sendika yasal grev kararı alır. İşveren, greve katılmayan 10 işçiyi fabrikada çalıştırarak üretime devam eder ve greve katılan işçilerin yerine de taşeron işçi alır. Bu durum yasal mıdır?", ideal_solution: "Grev ve Lokavt Kanununa göre, yasal grev sırasında greve katılmayan işçilerin işyerinde çalışmasına engel olunamaz (Grev kırıcı olmamak şartıyla). Ancak işveren, greve katılan işçilerin KADROLARI YERİNE hiçbir şekilde daimi veya geçici (taşeron) İŞÇİ ALAMAZ. İşverenin greve katılanların yerine dışarıdan işçi getirmesi açıkça kanuna aykırıdır.", key_points: ["Yasal grev", "Greve katılmayan işçiler", "Grev yerine işçi alma yasağı"], topics: ["Toplu İş Hukuku", "Grev ve Lokavt"] },
    { course: "is_hukuku", title: "İş Hukuku - Altı İş Günü Süresi", difficulty: "kolay", scenario: "İşveren, muhasebecisi (K)'nın zimmetine para geçirdiğini 1 Ocak'ta öğrenir. İşveren ancak 10 Ocak tarihinde (K)'yı haklı nedenle derhal fesih yoluyla (İş K. m.25/II) işten çıkarır. (K) itiraz eder.", ideal_solution: "İş K. m.26 uyarınca, ahlak ve iyiniyet kurallarına uymayan hallere (m.25/II) dayanarak haklı nedenle fesih yetkisi, olayın öğrenildiği tarihten itibaren ALTI İŞ GÜNÜ içinde kullanılmalıdır. İşveren 1 Ocak'ta öğrenip 10 Ocak'ta feshettiği için hak düşürücü süreyi kaçırmıştır. Fesih HAKSIZ feshe dönüşmüştür, (K) kıdem ve ihbar tazminatı isteyebilir.", key_points: ["Ahlak ve iyiniyet", "6 iş günü süresi", "Hak düşürücü süre", "Haksız fesih"], topics: ["Sözleşmenin Feshi", "Haklı Nedenle Fesih"] },
    { course: "is_hukuku", title: "İş Hukuku - Toplu İş Sözleşmesi Yetkisi", difficulty: "zor", scenario: "Bir işyerinde çalışan 100 işçinin 45'i A sendikasına, 30'u B sendikasına üyedir. Kalan işçiler sendikasızdır. A sendikası Toplu İş Sözleşmesi (TİS) yapmak için Bakanlığa yetki tespiti başvurusu yapar. Yetki verilir mi?", ideal_solution: "Sendikalar ve Toplu İş Sözleşmesi Kanununa göre, işyeri düzeyinde TİS yapabilmek için sendikanın işyerinde çalışan işçilerin YARISINDAN FAZLASININ (Yarıdan bir fazla, %50+1) kendi üyesi olması gerekir (İşyeri barajı). Ayrıca o işkolunda %1 işkolu barajını geçmesi gerekir. Olayda 100 işçinin yarısından fazlası 51 yapar. A sendikasının üye sayısı 45'tir. Bu nedenle A sendikası çoğunluğu sağlayamadığı için TİS yetkisi ALAMAZ.", key_points: ["Toplu İş Sözleşmesi", "Yetki tespiti", "Yarıdan fazla (%50+1) şartı"], topics: ["Toplu İş Hukuku", "Toplu İş Sözleşmesi"] }
  ],
  "milletlerarasi_ozel": [
    { course: "milletlerarasi_ozel", title: "MÖHUK - Boşanmada Uygulanacak Hukuk", difficulty: "zor", scenario: "Biri Alman diğeri Fransız vatandaşı olan ve Müşterek yerleşim yerleri İngiltere olan bir çift, tatil için geldikleri Türkiye'de şiddetli geçimsizlik nedeniyle Ankara mahkemesinde boşanma davası açarlar. Türk hakimi hangi hukuku uygulamalıdır?", ideal_solution: "MÖHUK m.14'e göre boşanma ve ayrılık sebepleri ve hükümleri, eşlerin müşterek milli hukukuna tabidir. Tarafların uyrukları farklı (Alman ve Fransız) olduğu için müşterek milli hukuk yoktur. Bu durumda tarafların MÜŞTEREK MUTAD MESKEN (yerleşim yeri) hukukuna bakılır. Olayda eşlerin müşterek yerleşim yeri İngiltere'dir. Dolayısıyla Türk Hakimi, boşanma davasında İngiliz maddi hukukunu (İngiliz Medeni Kanununu) uygulamalıdır.", key_points: ["Boşanmada uygulanacak hukuk (MÖHUK m.14)", "Müşterek milli hukuk", "Müşterek mutad mesken hukuku"], topics: ["Kanunlar İhtilafı", "Aile Hukuku (Boşanma)"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Sözleşmeden Doğan Borçlar (Lex Causae)", difficulty: "orta", scenario: "Türkiye'deki bir tekstil firması (T), İtalya'daki bir mağazaya (İ) kumaş satışı için sözleşme yapar. Sözleşmede uygulanacak hukuk seçilmemiştir. İtalyan firma kumaşların kusurlu olduğunu iddia ederek Türk mahkemesinde dava açar. Hangi hukuk uygulanır?", ideal_solution: "MÖHUK m.24'e göre, sözleşmeden doğan borç ilişkilerinde tarafların açıkça veya zımnen seçtikleri hukuk uygulanır. Hukuk seçimi yoksa, sözleşmeyle 'en sıkı ilişkili' olan hukuk uygulanır. Kanun, en sıkı ilişkili hukukun, karakteristik edim borçlusunun işyeri veya yerleşim yeri hukuku olduğunu karine olarak kabul eder. Satış sözleşmesinde karakteristik edim 'malın teslimi' yani satıcının (T) edimidir. Bu nedenle Türk hukuku sözleşmeyle en sıkı ilişkili hukuk kabul edilir ve uygulanır.", key_points: ["Hukuk seçimi yokluğu", "En sıkı ilişkili hukuk (MÖHUK m.24)", "Karakteristik edim borçlusu", "Türk Hukuku"], topics: ["Kanunlar İhtilafı", "Borçlar Hukuku (Sözleşmeler)"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Kamu Düzeni Müdahalesi", difficulty: "orta", scenario: "İran uyruklu birbirinin kuzeni olan (amca çocukları) (E) ve (K), Türkiye'de evlenmek için evlendirme memurluğuna başvururlar. İran hukukunda kuzen evliliği serbesttir. Türk makamları bu evliliği yapabilir mi?", ideal_solution: "MÖHUK m.13'e göre evlenme ehliyeti ve şartları her iki eşin kendi milli hukukuna tabidir. İran hukukuna göre evlenmelerinde engel yoktur. Ancak, yabancı hukukun uygulanması Türk Kamu Düzenine (MÖHUK m.5) 'açıkça aykırı' ise o hüküm uygulanmaz. TMK m.129'a göre amca çocukları arasında evlenme yasağı vardır (mutlak butlan). Ancak Türk hukukundaki kuzen evliliği yasağı milletlerarası kamu düzeni oluşturacak kadar evrensel ve ağır bir ahlaki/hukuki temel teşkil etmez (Yargıtay içtihatları). Dolayısıyla kamu düzeni engeline takılmaz ve evlilik yapılabilir.", key_points: ["Evlenme şartları (MÖHUK m.13)", "Kamu düzeni müdahalesi (MÖHUK m.5)", "Kuzen evliliği"], topics: ["Kanunlar İhtilafı", "Kamu Düzeni"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Tenfiz Kararı Şartları", difficulty: "zor", scenario: "Fransız mahkemesi, Türk vatandaşı (A)'nın gıyabında, ona usulüne uygun hiçbir tebligat yapmadan ve savunma hakkı vermeden (A) aleyhine 1 Milyon Euro tazminat ödemesine karar verir. Alacaklı bu kararın Türkiye'de tenfizi için dava açar.", ideal_solution: "MÖHUK m.54 uyarınca tenfiz şartlarından biri de 'O yerin kanunları uyarınca, kendisine karşı tenfiz istenen kişinin hükmü veren mahkemeye usulüne uygun bir şekilde çağrılmamış veya o mahkemede temsil edilmemiş...' olmamasıdır (Savunma hakkının ihlal edilmemesi). Olayda gıyapta ve tebligatsız, savunma hakkı verilmeden kurulan hüküm Türk mahkemelerince tenfiz edilemez (MÖHUK m.54/ç).", key_points: ["Tenfiz şartları (MÖHUK m.54)", "Savunma hakkının kısıtlanması", "Tebligat yokluğu", "Tenfizin reddi"], topics: ["Milletlerarası Usul Hukuku", "Tenfiz"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Münhasır Yetki İstisnası", difficulty: "kolay", scenario: "Alman mahkemesi, Antalya'daki bir taşınmazın mülkiyetinin Alman vatandaşı (X)'e ait olduğuna karar verir. (X) bu kararı Türkiye'de tanıtabilir mi?", ideal_solution: "MÖHUK m.54/b uyarınca, yabancı mahkeme kararının Türkiye'de tenfiz/tanıma alabilmesi için kararın 'Türk mahkemelerinin münhasır yetkisine girmeyen bir konuda' verilmiş olması şarttır. Türkiye'deki taşınmazın ayni haklarına ilişkin davalar Türk mahkemelerinin MÜNHASIR yetkisindedir (HMK m.12). Bu nedenle Alman mahkemesinin Antalya'daki taşınmazın mülkiyeti hakkındaki kararı Türkiye'de ASLA tanınamaz ve tenfiz edilemez.", key_points: ["Münhasır yetki", "Taşınmazın ayni hakkı", "Tenfiz şartı"], topics: ["Milletlerarası Usul Hukuku", "Tanıma ve Tenfiz"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Hak Ehliyeti ve Fiil Ehliyeti", difficulty: "orta", scenario: "Türkiye'de ticaret yapan 19 yaşındaki İsviçre vatandaşı (G), bir Türk firmasıyla ticari sözleşme imzalar. İsviçre hukukunda erginlik yaşı 20'dir. G, 'Ben İsviçre hukukuna göre ergin değilim, işlem geçersizdir' diyebilir mi?", ideal_solution: "MÖHUK m.9'a göre, hak ve fiil ehliyeti kişinin milli hukukuna tabidir (Yani İsviçre hukuku). Ancak MÖHUK m.9/2'de işlem güvenliğini koruyan bir istisna vardır: 'Kişi kendi milli hukukuna göre ehliyetsiz, ancak İŞLEMİN YAPILDIĞI YER (Türkiye) hukukuna göre ehliyetli ise, bu hukuki işlem GEÇERLİDİR'. Türk hukukuna göre 18 yaşını dolduran ergin olduğundan işlem tamamen geçerlidir.", key_points: ["Fiil ehliyeti (MÖHUK m.9)", "Milli Hukuk", "İşlem yeri hukuku istisnası", "İşlem güvenliği"], topics: ["Kanunlar İhtilafı", "Kişiler Hukuku"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Miras Hukuku", difficulty: "orta", scenario: "Türkiye'de yaşayan Alman vatandaşı (H) vefat eder. (H)'nin Türkiye'de bir dairesi, bir banka hesabı ve arabası vardır. Hangi mallarına hangi devletin miras hukuku uygulanacaktır?", ideal_solution: "MÖHUK m.20'ye göre miras, ölenin milli hukukuna tabidir (Alman hukuku). Ancak Türkiye'de bulunan TAŞINMAZLAR (daire) için Türk Hukuku uygulanır. Yani (H)'nin banka hesabı ve arabasına (taşınır mallarına) Alman miras hukuku, Türkiye'deki dairesine (taşınmaz) ise Türk miras hukuku uygulanacaktır.", key_points: ["Miras (MÖHUK m.20)", "Milli hukuk kuralı", "Taşınmaz istisnası (Türk Hukuku)"], topics: ["Kanunlar İhtilafı", "Miras Hukuku"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Ehliyetin Sonradan Kazanılması", difficulty: "kolay", scenario: "Milli hukukuna göre ehliyetli olan ve işlem yapan bir kişi, sonradan vatandaşlığını değiştirir ve yeni milli hukukuna göre ehliyetsiz sayılırsa eski işlemi geçersiz olur mu?", ideal_solution: "MÖHUK m.9/3'e göre; milli hukukuna göre fiil ehliyetine sahip olan bir kişi, sonradan tabiiyetini (vatandaşlığını) değiştirirse, fiil ehliyetini kaybetmez (Müktesep hak / kazanılmış hak). Yani sonradan ehliyetsiz hale gelse bile geçmişe etkili olmaz, işlemi geçerliliğini korur.", key_points: ["Vatandaşlık değişimi", "Ehliyetin korunması", "MÖHUK m.9/3"], topics: ["Kanunlar İhtilafı", "Kişiler Hukuku"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Tüketici Sözleşmeleri", difficulty: "zor", scenario: "Türkiye'de oturan tüketici (T), Amerikan firmasından (A) internet üzerinden bir laptop satın alır. Sözleşmede Amerikan hukukunun uygulanacağı yazar. Laptop bozuk çıkar. (T), Türk mahkemesinde dava açar.", ideal_solution: "MÖHUK m.26 uyarınca tüketici sözleşmelerinde taraflar hukuk seçebilir (Amerikan hukuku). Ancak bu seçim, TÜKETİCİNİN MUTAD MESKENİ (Türkiye) hukukunun emredici kurallarının tüketiciye sağladığı asgari korumadan onu yoksun bırakamaz. Yani Amerikan hukuku uygulansa bile, TKHK (Türk Tüketici Kanunu) kurallarından daha aleyhe bir hüküm içeriyorsa, Türk hukukunun emredici hükümleri devreye girer.", key_points: ["Tüketici sözleşmeleri (MÖHUK m.26)", "Asgari koruma ilkesi", "Mutad mesken hukuku"], topics: ["Kanunlar İhtilafı", "Borçlar Hukuku (Sözleşmeler)"] },
    { course: "milletlerarasi_ozel", title: "MÖHUK - Yabancıların Çalışma İzni", difficulty: "kolay", scenario: "Turist vizesiyle Türkiye'ye gelen İngiliz vatandaşı (İ), bir restoranda garson olarak çalışmaya başlar. Herhangi bir izin almamıştır. Yaptırımı nedir?", ideal_solution: "6735 sayılı Uluslararası İşgücü Kanunu'na göre, yabancıların Türkiye'de bağımlı veya bağımsız çalışabilmeleri için Çalışma ve Sosyal Güvenlik Bakanlığından 'Çalışma İzni' almaları zorunludur. İzni olmadan kaçak çalışan yabancıya ve onu çalıştıran işverene idari para cezası verilir ve yabancı sınır dışı (deport) edilir.", key_points: ["Yabancıların çalışması", "Çalışma izni", "Sınır dışı etme"], topics: ["Yabancılar Hukuku", "Çalışma Hakkı"] }
  ]
};

for (let course in cases) {
  appendCases(`${course}.json`, cases[course]);
}

console.log('Appended AUHF Bulk 1 Cases to data successfully.');
