const fs = require('fs');
const path = require('path');

const dir = path.join('/Users/efekarakoyun/hukukçalışma/uygulama/frontend/data/practice_cases');

function appendCases(filename, newCases) {
  const filePath = path.join(dir, filename);
  let data = [];
  if (fs.existsSync(filePath)) {
    try { data = JSON.parse(fs.readFileSync(filePath, 'utf-8')); } catch(e) {}
  }
  let startIdx = data.length + 900; 
  newCases.forEach((c, idx) => {
    c.id = `${c.course}_AUHF_BULK2_${startIdx + idx}`;
    data.unshift(c); 
  });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

const cases = {
  "kiymetli_evrak": [
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Emre Yazılı Senedin Ciro Edilmesi", difficulty: "kolay", scenario: "(A), emre yazılı bir bono düzenleyerek (B)'ye verir. (B), senedin arkasına sadece imzasını atarak senedi (C)'ye devreder. (C), senedin meşru hamili midir?", ideal_solution: "(B)'nin senedin arkasına sadece imzasını atması 'Beyaz Ciro'dur (TTK m.683). Beyaz ciro ile birlikte senedin zilyetliğinin (C)'ye geçirilmesi, senedin devri için yeterlidir. Emre yazılı senetler ciro ve teslim ile devredilir. (C), senedin meşru (haklı) hamilidir.", key_points: ["Emre yazılı senet", "Beyaz ciro", "Teslim ve ciro zinciri"], topics: ["Kambiyo Senetleri", "Ciro"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Açık (Beyaz) Bono", difficulty: "orta", scenario: "(M), acil nakde ihtiyacı olduğu için (N)'den borç alır ve sadece imzasını atarak boş bir bono kağıdını (N)'ye verir. (N), alacağı 10.000 TL olmasına rağmen senedi 100.000 TL olarak doldurur ve bankaya tahsile verir. (M)'nin savunması ne olabilir?", ideal_solution: "TTK m.680 uyarınca, tedavüle çıkarılırken tamamen doldurulmamış olan bonoya 'Açık Bono' (beyaz poliçe) denir. Açık bono düzenlenmesi geçerlidir ve doldurma yetkisi alacaklıya verilmiş sayılır. Ancak aralarındaki anlaşmaya aykırı doldurulursa (10.000 yerine 100.000), borçlu (M) bunu 'anlaşmaya aykırı doldurulduğu' (kişisel defi) gerekçesiyle lehtara (N)'ye karşı İLERİ SÜREBİLİR. İspat yükü (M)'dedir (Yazılı delil gerekir). Ancak (N) senedi iyiniyetli 3. kişiye devrederse, (M) bu savunmayı 3. kişiye karşı yapamaz.", key_points: ["Açık (beyaz) bono", "Anlaşmaya aykırı doldurma", "Kişisel defi", "İspat yükü"], topics: ["Kambiyo Senetleri", "Bono", "Def'iler"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Çekin Süresinde İbraz Edilmemesi", difficulty: "orta", scenario: "Ankara'da düzenlenip Ankara'da ödenecek olan (Aynı yerde ödenecek) bir çek, keşide tarihi olan 01.05.2025'ten 20 gün sonra (21.05.2025) hamil tarafından bankaya ibraz edilir. Banka karşılığı olmasına rağmen ödeme yapmaz. Hamil kime başvurabilir?", ideal_solution: "TTK m.796'ya göre, bir çek düzenlendiği yerde ödenecekse 10 GÜN içinde muhatap bankaya ibraz edilmelidir. Hamil bu süreyi kaçırmıştır (20 gün geçmiş). Süresinde ibraz edilmeyen çek, 'ÇEK NİTELİĞİNİ KAYBETMEZ' ancak hamil, müracaat borçlularına (cirantalara) başvuru hakkını KAYBEDER. Hamil sadece keşideciye (ve eğer çekin karşılığı bankada kalmışsa şans eseri tahsil edebilir ancak banka ödemek zorunda değildir) başvurabilir, o da sebepsiz zenginleşme hükümlerine (TTK m.732) göre olur.", key_points: ["İbraz süreleri (10 gün)", "Müracaat hakkının kaybı", "Sebepsiz zenginleşme davası"], topics: ["Kambiyo Senetleri", "Çek", "İbraz"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Hatır Senedi", difficulty: "zor", scenario: "(K), bankadan kredi çekmek isteyen arkadaşı (L)'ye yardımcı olmak için aslında ona hiçbir borcu olmadığı halde (L) lehine 50.000 TL'lik bir bono düzenler. (L) bu senedi bankaya (B) kredi teminatı olarak ciro eder. Banka senedi tahsil etmek için (K)'ya başvurduğunda (K) borcu olmadığını iddia eder.", ideal_solution: "Taraflar arasında borç olmadığı halde sırf kredi vb. sağlamak için düzenlenen senetlere 'Hatır Senedi' denir. Hatır senedi savunması (bedelsizlik defi), sadece aralarında bu hatır ilişkisi olan taraflara (K ile L) karşı ileri sürülebilir. Bu bir KİŞİSEL DEF'İDİR (TTK m.687). Çeki/bonoyu devralan banka (B), senedi devralırken bile bile borçlunun zararına (kötü niyetle) hareket etmediği sürece, (K) hatır senedi def'ini bankaya karşı İLERİ SÜREMEZ. Bankaya ödeme yapmak zorundadır.", key_points: ["Hatır senedi", "Kişisel defi", "Üçüncü kişiye karşı ileri sürülememesi (TTK m.687)", "Kötüniyet istisnası"], topics: ["Kambiyo Senetleri", "Bono", "Def'iler"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Sahte İmza Def'i", difficulty: "orta", scenario: "Bir poliçe üzerindeki keşideci (A)'nın imzası, (X) tarafından taklit edilerek atılmıştır (sahte imza). Poliçe (B)'ye, oradan da iyi niyetli (C)'ye ciro edilmiştir. (C), (A)'ya başvurduğunda (A) imzanın kendisine ait olmadığını belirtir.", ideal_solution: "Sahte imza, senet metninden anlaşılamasa da 'Mutlak Defi' niteliğindedir (TTK m.677 atfıyla geçerlilik def'i). Mutlak defiler herkese karşı, hatta senedi devralan iyiniyetli 3. kişilere (C'ye) karşı da ileri sürülebilir. (A), imzanın kendisine ait olmadığını ispatladığında (C)'ye ödeme yapmaktan kurtulur. Ancak 'imzaların bağımsızlığı ilkesi' gereği (TTK m.678), sahte imza dışındaki diğer geçerli imzaların sahipleri (örneğin B) senedin bedelinden (C)'ye karşı sorumludur.", key_points: ["Sahte imza", "Mutlak defi", "Herkese karşı ileri sürülebilirlik", "İmzaların bağımsızlığı ilkesi (TTK m.678)"], topics: ["Kambiyo Senetleri", "Poliçe", "Def'iler"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Çizgili Çek", difficulty: "kolay", scenario: "(Y), (Z)'ye verdiği çekin ön yüzüne paralel iki çizgi çeker. Bunun anlamı nedir ve banka kime ödeme yapabilir?", ideal_solution: "Ön yüzüne birbirine paralel iki çizgi çekilen çeke 'Çizgili Çek' denir (TTK m.803). Çizgili çekin amacı, çekin hırsızlık veya kaybolma riskine karşı korunmasıdır. Çizgili çeki muhatap banka, sadece MÜŞTERİSİNE veya BİR BAŞKA BANKAYA ödeyebilir. Doğrudan gişeden elden nakit ödeme yapamaz, mutlaka hesaba geçirilmesi gerekir.", key_points: ["Çizgili çek", "TTK m.803", "Sadece bankaya veya müşteriye ödeme"], topics: ["Kambiyo Senetleri", "Çek"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Postadan Gecikme (İbraz Süresi)", difficulty: "zor", scenario: "Hamil (H), çeki bankaya ibraz etmek üzere posta/kargo ile gönderir. Ancak kargo şirketinin kaza yapması nedeniyle çek, 10 günlük ibraz süresi bittikten sonra bankaya ulaşır. Mücbir sebep midir?", ideal_solution: "TTK m.811 uyarınca, kanuni süresi içinde çekin ibrazı veya protesto edilmesi devletin bir kanunu veya aşılamaz bir engel (mücbir sebep) nedeniyle yapılamamışsa süreler UZAR. Ancak posta veya kargodaki gecikmeler Yargıtay tarafından mücbir sebep olarak KABUL EDİLMEMEKTEDİR. Hamil, şahsen ibraz etme riskini üzerine almıştır. Süre kaçtığı için müracaat hakkı düşer.", key_points: ["Mücbir sebep", "Posta gecikmesi (Mücbir sebep sayılmaz)", "İbraz süresinin uzamaması"], topics: ["Kambiyo Senetleri", "Çek", "İbraz"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Nama Yazılı Senet", difficulty: "kolay", scenario: "Üzerinde '(B) adına ödeyiniz, emre değildir' yazan senedin hukuki niteliği nedir ve nasıl devredilir?", ideal_solution: "Üzerinde 'emre değildir' (menfi emre şartı) ibaresi bulunan senetler, kural olarak emre yazılı olsalar bile (kambiyo senetleri böyledir), bu ibare nedeniyle 'Nama Yazılı Senet' hükmündedirler (TTK m.823). Nama yazılı senetler ciro ile değil, ancak 'Yazılı Devir Beyanı (Alacağın Temliki)' ve 'Senedin Teslimi' ile devredilebilirler.", key_points: ["Nama yazılı senet", "Menfi emre şartı", "Alacağın temliki yoluyla devir"], topics: ["Kıymetli Evrakın Türleri", "Nama Yazılı Senetler"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Poliçede Kabul", difficulty: "orta", scenario: "Poliçede muhatap (M), poliçenin ön yüzüne sadece imzasını atmıştır. Bu imzanın anlamı nedir?", ideal_solution: "TTK m.696'ya göre, muhatabın poliçenin 'ÖN YÜZÜNE' sadece imzasını atması KABUL hükmündedir. Muhatap, kabul ile birlikte poliçenin asli borçlusu haline gelir ve vade geldiğinde poliçe bedelini ödemeyi taahhüt etmiş olur.", key_points: ["Poliçede muhatap", "Ön yüze atılan imza", "Kabul hükmünde olması", "Asli borçlu"], topics: ["Kambiyo Senetleri", "Poliçe", "Kabul"] },
    { course: "kiymetli_evrak", title: "Kıymetli Evrak - Çekte Vade", difficulty: "kolay", scenario: "(X), 01.01.2025'te düzenlediği çeke düzenleme (keşide) tarihi olarak ileri bir tarih olan 01.06.2025 yazar. Ancak hamil çeki 05.01.2025'te bankaya ibraz eder. Banka ne yapmalıdır?", ideal_solution: "TTK m.795'e göre çekte vade yoktur; çek GÖRÜLDÜĞÜNDE ÖDENİR. İleri tarihli (postdated) çekler, üzerindeki tarihten önce bankaya ibraz edilirse (eğer hesapta para varsa) banka tarafından ÖDENMEK ZORUNDADIR. (Geçici kanuni düzenlemelerle getirilen karşılıksız işlem yapılamayacağına dair istisnalar saklı kalmak kaydıyla genel kural budur).", key_points: ["Çekte vade yasağı", "İleri tarihli çek", "Görüldüğünde ödenme (TTK m.795)"], topics: ["Kambiyo Senetleri", "Çek"] }
  ],
  "icra_iflas": [
    { course: "icra_iflas", title: "İcra ve İflas - İlamsız Takipte Yetki İtirazı", difficulty: "orta", scenario: "İstanbul'da ikamet eden borçlu (B) aleyhine, İzmir İcra Dairesinde ilamsız icra takibi başlatılır. (B), İzmir İcra Dairesinin yetkisiz olduğunu düşünmektedir. İtirazını nereye ve ne kadar sürede yapmalıdır?", ideal_solution: "İlamsız icra takibinde yetki kuralları HMK m.6 atfıyla belirlenir (Borçlunun yerleşim yeri esastır). Yetki itirazı bir İLK İTİRAZDIR ve ödeme emrinin tebliğinden itibaren 7 GÜN içinde ESAS İCRA DAİRESİNE (İzmir İcra Dairesine) dilekçe veya sözlü beyanla yapılmalıdır. İcra mahkemesine değil, doğrudan takibin yapıldığı icra dairesine yapılır (İİK m.50).", key_points: ["İlamsız icra", "Yetki itirazı", "7 gün süre", "İcra dairesine başvuru", "İİK m.50"], topics: ["İlamsız İcra", "Ödeme Emrine İtiraz"] },
    { course: "icra_iflas", title: "İcra ve İflas - Gecikmiş İtiraz", difficulty: "zor", scenario: "Borçlu (C) ağır bir trafik kazası geçirip komadayken aleyhine başlatılan ilamsız takipte ödeme emri eşine tebliğ edilir ve 7 günlük itiraz süresi geçer. (C) iyileşip durumu öğrendiğinde ne yapabilir?", ideal_solution: "İİK m.65'e göre, borçlu kusuru olmaksızın bir MÜCBİR SEBEP (ağır hastalık, koma) nedeniyle süresi içinde itiraz edememişse, 'Gecikmiş İtiraz' kurumuna başvurabilir. Gecikmiş itiraz, engelin kalktığı (iyileştiği) tarihten itibaren 3 GÜN İÇİNDE İcra Mahkemesine (İcra Dairesine değil) yapılır. Mahkeme mazereti haklı bulursa itirazı kabul eder ve takibi durdurur.", key_points: ["Gecikmiş itiraz (İİK m.65)", "Mücbir sebep", "Engelin kalkmasından itibaren 3 gün", "İcra mahkemesine başvuru"], topics: ["İlamsız İcra", "Ödeme Emrine İtiraz"] },
    { course: "icra_iflas", title: "İcra ve İflas - Haczedilmezlik (Meslek Aletleri)", difficulty: "kolay", scenario: "Taksicilik yaparak geçimini sağlayan (T)'nin tek taksisi, alacaklı (A) tarafından haczettirilir. (T), taksinin haczedilemeyeceğini iddia eder. Haklı mıdır?", ideal_solution: "İİK m.82/1-4'e göre, borçlunun 'mesleğini sürdürebilmesi için gerekli olan her türlü alet, edevat ve kitapları' HACZEDİLEMEZ. Şoför/Taksici için taksi, mesleğin icrası için zorunlu ve temel alet niteliğindedir (Yargıtay içtihatları da bu yöndedir). Dolayısıyla (T)'nin mesleğini devam ettirdiği tek taksisi haczedilemez. (T), İcra Mahkemesine şikayet yoluyla (7 gün içinde) başvurarak haczin kaldırılmasını isteyebilir.", key_points: ["Haczedilmezlik", "Meslek aletleri (İİK m.82)", "İcra mahkemesine şikayet"], topics: ["Haciz", "Haczedilemeyen Mallar"] },
    { course: "icra_iflas", title: "İcra ve İflas - İtirazın İptali ve İcra İnkar Tazminatı", difficulty: "zor", scenario: "Fatura alacağına dayanan ilamsız takipte borçlu haksız yere borca itiraz eder ve takip durur. Alacaklı 1 yıl içinde Asliye Hukuk Mahkemesinde İtirazın İptali Davası açar ve kazanır. Alacaklı ayrıca ne talep edebilir?", ideal_solution: "İİK m.67 uyarınca alacaklı, itirazın iptali davasını kazanırsa, borçlunun haksız itirazı nedeniyle ve alacağın 'LİKİT (belirlenebilir)' olması şartıyla, alacak tutarının %20'sinden aşağı olmamak üzere 'İcra İnkar Tazminatına' hükmedilmesini isteyebilir. Fatura alacağı likit bir alacak olduğundan mahkeme, borçlunun (haksız olduğu anlaşıldığı için) %20 oranında inkar tazminatı ödemesine hükmeder.", key_points: ["İtirazın iptali davası (İİK m.67)", "1 yıllık süre", "Likit alacak", "%20 İcra İnkar Tazminatı"], topics: ["İlamsız İcra", "İtirazın Hükümden Düşürülmesi"] },
    { course: "icra_iflas", title: "İcra ve İflas - Kambiyo Senetlerine Özgü Takip", difficulty: "orta", scenario: "Alacaklı (A), elindeki senede dayanarak kambiyo senetlerine özgü haciz yoluyla takip başlatır. Ancak İcra Müdürü, senedin bono vasfı taşımadığını (zorunlu unsurlarının eksik olduğunu) tespit eder. İcra müdürü ne yapmalıdır?", ideal_solution: "İİK m.170/a ve Yargıtay içtihatlarına göre icra müdürü, kambiyo takibi talebi geldiğinde senedin kambiyo vasfı taşıyıp taşımadığını ve vadenin gelip gelmediğini RE'SEN (kendiliğinden) incelemek ZORUNDADIR. Eğer senet bono vasfı taşımıyorsa, icra müdürü takip talebini reddetmeli ve ödeme emri GÖNDERMEMELİDİR. Gönderirse, borçlu 5 gün içinde İcra Mahkemesine şikayet yoluna başvurabilir.", key_points: ["Kambiyo takibi", "İcra müdürünün re'sen inceleme yetkisi", "Kambiyo vasfı"], topics: ["Kambiyo Senetlerine Özgü Haciz Yolu"] },
    { course: "icra_iflas", title: "İcra ve İflas - İflasın Ertelenmesi ve Konkordato", difficulty: "kolay", scenario: "Mali durumu bozulan bir anonim şirket, iflastan kurtulmak için iflasın ertelenmesi kurumuna başvurmak ister. Bu günümüzde mümkün müdür?", ideal_solution: "Hayır. 2018 yılında İcra ve İflas Kanunu'nda yapılan büyük değişiklikle 'İflasın Ertelenmesi' kurumu tamamen KALDIRILMIŞTIR. Bunun yerine 'Konkordato' kurumu yeniden düzenlenmiş ve güçlendirilmiştir. Şirket, Asliye Ticaret Mahkemesinden konkordato mühleti talep etmelidir.", key_points: ["İflasın ertelenmesi mülga", "Konkordato kurumunun önceliği", "2018 yasa değişikliği"], topics: ["İflas Hukuku", "Konkordato"] },
    { course: "icra_iflas", title: "İcra ve İflas - Sıra Cetveline İtiraz", difficulty: "orta", scenario: "İflas masasına giren alacakların ödenmesi için iflas idaresi tarafından hazırlanan Sıra Cetvelinde (A), kendi sırasının yanlış olduğunu düşünmektedir. Nereye ve nasıl başvurmalıdır?", ideal_solution: "Sıra cetveline itiraz iki farklı sebeple yapılabilir. Eğer (A) sadece 'sırasına' (öncelik hakkına) veya 'hukuki yoruma/icra dairesinin işlemine' itiraz ediyorsa (yani başkasının alacağına değil kendi sırasına), 7 GÜN içinde İcra Mahkemesine ŞİKAYET yoluyla başvurur. Eğer (A), cetvele alınan başka bir alacaklının alacağının esasına veya miktarına (böyle bir borç yoktur diyerek) itiraz ediyorsa, 15 GÜN içinde Asliye Ticaret Mahkemesinde (veya genel mahkemelerde) SIRA CETVELİNE İTİRAZ DAVASI açmalıdır.", key_points: ["Sıra cetveli", "Sıraya şikayet (İcra Mahkemesi - 7 gün)", "Esasa itiraz (Genel Mahkeme - 15 gün)"], topics: ["İflas Hukuku", "İflas Tasfiyesi"] },
    { course: "icra_iflas", title: "İcra ve İflas - Hacze İştirak", difficulty: "zor", scenario: "(B)'nin maaşına (A) tarafından haciz konulmuştur ve kesintiler devam etmektedir. Daha sonra (C)'nin başlattığı takip kesinleşir ve (C) de maaş haczine iştirak etmek ister. (C)'nin alacağı ilama (mahkeme kararına) dayanmaktadır. İştirak mümkün müdür?", ideal_solution: "İİK m.100'e göre 'İmtiyazlı Hacze İştirak' için, sonradan gelen alacaklının alacağının, ilk haczin İHTİYATİ veya İCRASİ olarak KESİNLEŞTİĞİ TARİHTEN ÖNCE (önceki bir tarihte) alınmış bir İLAMA (veya resmi belgeye) dayanması gerekir. Eğer (C)'nin ilamı ilk haciz tarihinden öncesine aitse, ilk hacze iştirak edebilir ve haczedilen malların (maaşın) satış bedeli ikisi arasında garame (orantılı) paylaştırılır.", key_points: ["Hacze iştirak (İİK m.100)", "İmtiyazlı iştirak şartları", "İlamın tarihi"], topics: ["Haciz", "Hacze İştirak"] },
    { course: "icra_iflas", title: "İcra ve İflas - Tasarrufun İptali Davası", difficulty: "orta", scenario: "Borca batık olan (B), hakkında icra takibi başlayacağını anlayınca tüm malvarlığını (tek evini) kayınbiraderi (K)'ya düşük bir bedelle satarak devreder. Alacaklı (A), bu satışı iptal ettirebilir mi?", ideal_solution: "Evet. İİK m.277 vd. uyarınca, borçlunun alacaklılarından mal kaçırmak amacıyla yaptığı tasarrufların iptali için 'Tasarrufun İptali Davası (Actio Pauliana)' açılabilir. İİK m.278'e göre (İvazsız tasarrufların iptali), borçlunun eşi, altsoyu, üstsoyu, kan veya kayın hısımları (3. derece dahil) ile yaptığı satışlar BAĞIŞLAMA GİBİ KABUL EDİLİR ve iptal edilebilir. Kayınbirader (K), 2. derece kayın hısmıdır. Mahkeme satışı iptal eder ve ev, (B)'nin malvarlığına geri dönmüş sayılarak (A) tarafından haczettirilip satılabilir.", key_points: ["Tasarrufun iptali davası", "İİK m.277-278", "Hısımlara satışın bağışlama sayılması", "Mal kaçırma kasti"], topics: ["Tasarrufun İptali Davası"] },
    { course: "icra_iflas", title: "İcra ve İflas - Şikayet Süresi ve Kamu Düzeni", difficulty: "kolay", scenario: "İcra Müdürü, borçluya ait bir taşınmazı ihale yoluyla satarken kanunda öngörülen asgari satış bedelinin çok altında bir bedele ihaleyi tamamlar (Kamu düzenine aykırı ağır hata). Borçlu 1 ay sonra şikayet eder. Şikayet süresi geçmiş midir?", ideal_solution: "Kural olarak icra müdürünün işlemlerine karşı şikayet süresi işlemin öğrenildiği tarihten itibaren 7 GÜNDÜR (İİK m.16). Ancak işlem 'Kamu düzenine' aykırıysa, SÜRESİZ ŞİKAYET yolu açıktır. Ağır usul hataları ve kamu düzenini bozan emredici kural ihlalleri süresiz şikayete tabidir. İcra Mahkemesi şikayeti kabul etmelidir.", key_points: ["İcra şikayeti", "7 günlük kural", "Süresiz şikayet istisnası", "Kamu düzeni (İİK m.16)"], topics: ["İcra Organları", "Şikayet"] }
  ],
  "genel_kamu": [
    { course: "genel_kamu", title: "Genel Kamu - Doğal Haklar Doktrini", difficulty: "kolay", scenario: "John Locke'un bahsettiği 'Doğal Haklar' nelerdir ve devlet bu hakları ortadan kaldırabilir mi?", ideal_solution: "Doğal haklar doktrinine (özellikle John Locke'a) göre, insanların doğuştan getirdiği devredilemez ve vazgeçilemez üç temel hak vardır: Yaşama, Özgürlük ve Mülkiyet hakları. Devlet (sivil toplum), bu hakları korumak için bir 'sosyal sözleşme' ile kurulmuştur. Dolayısıyla devlet, varlık sebebi olan bu doğal hakları ortadan kaldıramaz; aksine korumakla yükümlüdür.", key_points: ["Doğal haklar", "Locke", "Yaşama, Özgürlük, Mülkiyet", "Sosyal sözleşme"], topics: ["Devletin Kökeni", "Doğal Haklar"] },
    { course: "genel_kamu", title: "Genel Kamu - Montesquieu ve Kuvvetler Ayrılığı", difficulty: "orta", scenario: "Kuvvetler ayrılığı ilkesi kime aittir ve amacı nedir?", ideal_solution: "Kuvvetler Ayrılığı ilkesi, Montesquieu tarafından sistemleştirilmiştir ('Kanunların Ruhu Üzerine' adlı eserinde). Amacı, devlet içindeki yasama, yürütme ve yargı güçlerinin aynı elde toplanmasını engelleyerek mutlak monarşiyi (tiranlığı) önlemek ve vatandaşların siyasi özgürlüklerini güvence altına almaktır. 'Güç, gücü durdurmalıdır' felsefesine dayanır.", key_points: ["Kuvvetler Ayrılığı", "Montesquieu", "Güç gücü durdurmalıdır", "Özgürlüğün güvencesi"], topics: ["Devletin Unsurları", "Kuvvetler Ayrılığı"] },
    { course: "genel_kamu", title: "Genel Kamu - AİHM ve İç Hukuk Yollarının Tüketilmesi", difficulty: "zor", scenario: "Vatandaş (V), adil yargılanma hakkının ihlal edildiği gerekçesiyle Yargıtay kararından hemen sonra doğrudan Avrupa İnsan Hakları Mahkemesi'ne (AİHM) başvurur. AİHM başvuruyu kabul eder mi?", ideal_solution: "Hayır, kabul etmez. AİHS m.35 uyarınca, AİHM'e başvurabilmek için 'İç Hukuk Yollarının Tüketilmesi' şartı vardır. Türk hukuk sisteminde Anayasa Mahkemesine Bireysel Başvuru yolu mevcut olduğundan, Yargıtay kararından sonra öncelikle AYM'ye başvurulması (Anayasa m.148) zorunludur. AYM'den de ret kararı aldıktan sonra süresi içinde (4 ay) AİHM'e başvurulabilir.", key_points: ["AİHM", "İç hukuk yollarının tüketilmesi", "AYM Bireysel Başvuru"], topics: ["İnsan Hakları", "AİHM"] },
    { course: "genel_kamu", title: "Genel Kamu - Carl Schmitt ve Düşman/Dost Ayrımı", difficulty: "zor", scenario: "Carl Schmitt'e göre siyasal (politika) kavramının özü nedir?", ideal_solution: "Carl Schmitt'e göre siyasetin özü 'Dost ve Düşman' ayrımına dayanır. Ahlak için iyi-kötü, estetik için güzel-çirkin ne ise, siyaset için de dost-düşman ayrımı odur. Düşman, kamuya ait bir düşmandır (hostis) ve devletin/toplumun varlığını tehdit eden ötekidir.", key_points: ["Carl Schmitt", "Siyasal kavramı", "Dost-Düşman ayrımı"], topics: ["Siyaset Kuramları"] },
    { course: "genel_kamu", title: "Genel Kamu - Hukuk Devleti İlkeleri", difficulty: "orta", scenario: "Bir devletin 'Hukuk Devleti' sayılabilmesi için taşıması gereken olmazsa olmaz asgari şartlar (maddi ve şekli) nelerdir?", ideal_solution: "Hukuk devleti, idarenin eylem ve işlemlerinin hukuk kurallarına bağlı olduğu ve yargı denetimine tabi tutulduğu devlettir. Temel şartları: 1) Kanunların genelliği ve öngörülebilirliği, 2) Yargı bağımsızlığı ve tarafsızlığı, 3) İdarenin yargısal denetimi (İptal ve tam yargı davaları), 4) Temel hak ve hürriyetlerin güvence altına alınması, 5) İdarenin mali sorumluluğu, 6) Kanuni idare ilkesi ve idarenin kanuniliği.", key_points: ["Hukuk devleti", "Yargı denetimi", "Yargı bağımsızlığı", "Temel hak güvencesi"], topics: ["Devlet Türleri", "Hukuk Devleti"] },
    { course: "genel_kamu", title: "Genel Kamu - Rousseau ve Temsili Demokrasi Eleştirisi", difficulty: "orta", scenario: "Rousseau, temsili demokrasiyi (halkın temsilciler seçmesini) nasıl değerlendirir?", ideal_solution: "Rousseau, temsili demokrasiye şiddetle KARŞIDIR. Ona göre 'Egemenlik devredilemez'. İngiliz parlamenter sistemini eleştirerek, 'İngiliz halkı sadece seçim günlerinde özgürdür, seçim bittikten sonra tekrar köle olur' demiştir. Rousseau, halkın doğrudan yasa yaptığı Doğrudan Demokrasiyi savunur.", key_points: ["Rousseau", "Temsili demokrasi eleştirisi", "Doğrudan demokrasi", "Egemenlik devredilemez"], topics: ["Demokrasi Teorileri", "Rousseau"] },
    { course: "genel_kamu", title: "Genel Kamu - Machiavelli ve Amaca Giden Her Yol Mubahtır", difficulty: "kolay", scenario: "Prens adlı eserinde siyasetin ahlaktan bağımsız olduğunu savunan düşünür kimdir?", ideal_solution: "Niccolò Machiavelli'dir. 'Prens' (Il Principe) adlı eserinde devletin bekası ve siyasi gücün korunması için ahlaki değerlerin gerekirse bir kenara bırakılabileceğini savunmuştur (Amaca giden her yol mubahtır anlayışı - Makyavelizm). Ona göre devletin çıkarı her şeyin üstündedir.", key_points: ["Machiavelli", "Prens", "Ahlak ve siyaset ayrımı", "Devlet aklı (Raison d'etat)"], topics: ["Devletin Kökeni", "Machiavelli"] },
    { course: "genel_kamu", title: "Genel Kamu - AİHS Pozitif Yükümlülük", difficulty: "zor", scenario: "Devlet, AİHS m.2 Yaşam Hakkı kapsamında sadece vatandaşlarını öldürmemekle (negatif yükümlülük) mi mükelleftir?", ideal_solution: "Hayır. AİHM içtihatlarına göre Yaşam Hakkı (m.2) devlete sadece müdahale etmeme (öldürmeme) değil, aynı zamanda vatandaşlarının yaşamını üçüncü kişilerin veya doğa olaylarının tehlikelerinden koruma (Polis koruması sağlama, önleyici tedbirler alma vb.) 'POZİTİF YÜKÜMLÜLÜĞÜNÜ' de yükler. Ayrıca şüpheli ölümlerde etkili bir soruşturma yürütme zorunluluğu da (usuli pozitif yükümlülük) vardır.", key_points: ["Yaşam Hakkı (m.2)", "Pozitif yükümlülük", "Etkili soruşturma", "Devletin koruma ödevi"], topics: ["İnsan Hakları", "Yaşam Hakkı"] },
    { course: "genel_kamu", title: "Genel Kamu - Weber ve Devletin Şiddet Tekeli", difficulty: "orta", scenario: "Max Weber'e göre devleti tanımlayan en belirgin sosyolojik özellik nedir?", ideal_solution: "Max Weber devleti, 'belirli bir toprak parçası üzerinde MEŞRU FİZİKSEL ŞİDDET KULLANMA TEKELİNİ (tekel hakkını) başarıyla tekelinde bulunduran insan topluluğu (örgüt)' olarak tanımlar. Yani devlet dışında hiçbir grup veya kişinin meşru olarak güç/şiddet kullanma hakkı yoktur.", key_points: ["Max Weber", "Meşru şiddet tekeli", "Devletin tanımı"], topics: ["Devletin Unsurları"] },
    { course: "genel_kamu", title: "Genel Kamu - Üçüncü Kuşak İnsan Hakları", difficulty: "kolay", scenario: "Çevre hakkı, barış hakkı, gelişme hakkı gibi haklar hangi kuşak insan haklarıdır?", ideal_solution: "Bu haklar, Karel Vasak'ın tasnifine göre 'Üçüncü Kuşak (Dayanışma Hakları)' olarak adlandırılır. Birinci kuşak klasik sivil ve siyasi haklar (özgürlükler), ikinci kuşak ekonomik ve sosyal haklar (eşitlik) iken, üçüncü kuşak haklar küresel dayanışma gerektiren (kardeşlik) çevre, barış ve halkların kendi kaderini tayin hakkıdır.", key_points: ["Üçüncü kuşak haklar", "Dayanışma hakları", "Çevre hakkı", "Barış hakkı"], topics: ["İnsan Hakları", "Hakların Sınıflandırılması"] }
  ],
  "miras_hukuku": [
    { course: "miras_hukuku", title: "Miras Hukuku - Mirasbırakanın Tasarruf Özgürlüğü ve Saklı Pay", difficulty: "zor", scenario: "Mirasbırakan (M), vefat ettiğinde eşi (E) ve iki çocuğu (Ç1, Ç2) hayattadır. (M), ölmeden önce vasiyetname ile tüm malvarlığını (1.200.000 TL) yardım vakfına bırakmıştır. Mirasçıların saklı payları ne kadardır ve ne davası açabilirler?", ideal_solution: "Öncelikle yasal miras payları hesaplanır: Eşin yasal payı (1. zümre ile birlikte) mirasın 1/4'üdür. Çocukların yasal payı kalanın (3/4'ün) yarısı, yani 3/8'erdir. TMK m.506'ya göre saklı pay oranları; Altsoy (çocuklar) için yasal miras payının 1/2'si, eş için (1. veya 2. zümre ile birlikteyse) yasal miras payının TAMAMI'dır. Buna göre; Eşin saklı payı: 1/4 * 1 = 1/4 (300.000 TL). Çocukların saklı payı: 3/8 * 1/2 = 3/16'şar (225.000'er TL). Toplam saklı pay: 1/4 (4/16) + 3/16 + 3/16 = 10/16 (750.000 TL). Mirasbırakanın tasarruf edilebilir kısmı (serbest oranı) 1.200.000 - 750.000 = 450.000 TL'dir. Mirasçılar (E, Ç1, Ç2), kendi saklı paylarını ihlal eden vasiyetnameye karşı TENKİS DAVASI açarak vakıftan saklı paylarını geri alabilirler.", key_points: ["Yasal miras payı", "Saklı pay oranları (TMK m.506)", "Tenkis davası", "Tasarruf edilebilir kısım"], topics: ["Yasal Mirasçılar", "Saklı Pay", "Tenkis Davası"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Mirasçılıktan Çıkarma (Iskat)", difficulty: "orta", scenario: "Baba (B), sürekli kendisine şiddet uygulayan ve ağır hakaretler eden oğlu (O)'yu noterde düzenlediği vasiyetnameyle 'Bana şiddet uyguladığı için onu mirasçılıktan çıkarıyorum' diyerek mirastan ıskat eder. (O), babasının ölümünden sonra saklı payını isteyebilir mi?", ideal_solution: "TMK m.510'a göre 'Mirasçılıktan Çıkarma (Iskat)', mirasçının mirasbırakana veya yakınlarına karşı ağır bir suç işlemesi veya aile hukukundan doğan yükümlülüklerini ağır şekilde ihlal etmesi durumunda mümkündür. Olayda şiddet uygulama ağır bir ihlal ve suçtur. Geçerli bir çıkarma işlemi yapıldığından (O), yasal mirasçılık sıfatını kaybeder ve SAKLI PAYINI İSTEYEMEZ. Çıkarılan kimsenin payı (kendi altsoyu varsa onlara), yoksa mirasbırakanın diğer yasal mirasçılarına kalır.", key_points: ["Mirastan çıkarma (Iskat)", "Cezai ıskat (TMK m.510)", "Ağır suç/yükümlülük ihlali", "Saklı payın kaybı"], topics: ["Ölüme Bağlı Tasarruflar", "Mirasçılıktan Çıkarma"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Mirasın Reddi (Süresi ve Karinesi)", difficulty: "kolay", scenario: "Mirasbırakan borca batık olarak ölmüştür. Mirasçı (A), vefatı öğrendiği tarihten itibaren hiçbir işlem yapmadan 4 ay bekler. 5. ayda alacaklılar borç için icra takibi yapınca (A), 'Mirası reddediyorum' der. Geçerli midir?", ideal_solution: "TMK m.606'ya göre, miras 3 AY İÇİNDE reddolunabilir. Bu süre, yasal mirasçılar için mirasbırakanın ölümünü öğrendikleri tarihten itibaren başlar. Süresi içinde mirası reddetmeyen mirasçı, mirası KABUL ETMİŞ (kayıtsız şartsız) sayılır (TMK m.610). 4 ay geçtiği için ret geçersizdir. ANCAK; ölümü anında mirasbırakanın ÖDEMEDEN ACZİ AÇIKÇA BELLİ veya resmen tespit edilmişse, miras reddedilmiş sayılır (Hükmi Ret - TMK m.605/2). Olayda borca batıklık açıkça belli ise hükmi ret karinesi işler ve (A) kurtulabilir. Aksi halde borçlardan şahsen sorumludur.", key_points: ["Mirasın gerçek reddi (3 ay)", "Mirasın kabulü karinesi", "Hükmi ret (TMK m.605/2)", "Borca batıklık"], topics: ["Mirasın Geçmesi", "Mirasın Reddi"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Vasiyetnameden Dönme", difficulty: "kolay", scenario: "Mirasbırakan (M), 2020 yılında resmi vasiyetname ile arabasını (X)'e bırakır. 2025 yılında ise el yazılı vasiyetname ile aynı arabayı (Y)'ye bırakır. M vefat edince arabayı kim alır?", ideal_solution: "TMK m.542 uyarınca, mirasbırakan yeni bir ölüme bağlı tasarrufla önceki tasarrufundan her zaman dönebilir. Sonraki tasarruf, önceki ile çelişiyorsa sonrakine itibar edilir. El yazılı vasiyetname kanuni şartları taşıyorsa geçerlidir ve önceki resmi vasiyetnameyi o madde yönünden (araba bağlamında) hükümsüz kılar. Arabayı (Y) alır.", key_points: ["Vasiyetnameden dönme", "Sonraki tasarruf", "Şekil serbestisi", "TMK m.542"], topics: ["Ölüme Bağlı Tasarruflar", "Vasiyetname"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Mirasın Mirasçılara Geçişi (Külli Halefiyet)", difficulty: "orta", scenario: "Mirasbırakan ölür. Terekenin vergi borçları ve intikal işlemleri henüz yapılmamıştır. Mirasçılar, 'Biz daha tapuda intikalleri üzerimize almadık, evler bizim değil' diyebilirler mi?", ideal_solution: "TMK m.599'da düzenlenen 'Külli Halefiyet' ilkesine göre mirasçılar, mirasbırakanın ölümü ile mirası bir bütün olarak, kanun gereğince KENDİLİĞİNDEN kazanırlar. Mirasçıların mülkiyeti kazanmaları için tapuda tescil (intikal) işlemi yapmalarına veya başka bir tasarrufi işleme gerek yoktur. Tapudaki tescil sadece kurucu değil, bildirici (açıklayıcı) niteliktedir. O an itibariyle evlerin malikidirler ve borçlardan da sorumludurlar.", key_points: ["Külli halefiyet (TMK m.599)", "Kendiliğinden kazanma", "Bildirici tescil"], topics: ["Mirasın Geçmesi", "Külli Halefiyet"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Mirasçılık Belgesi (Veraset İlamı)", difficulty: "kolay", scenario: "Mirasçılar bankadaki parayı çekmek için Sulh Hukuk Mahkemesinden veya Noterden 'Mirasçılık Belgesi' alırlar. Daha sonra gaiplikten dönen başka bir mirasçı bu belgenin iptalini isteyebilir mi?", ideal_solution: "Mirasçılık belgesi (veraset ilamı), mirasçılık sıfatını gösteren aksi ispat edilene kadar geçerli olan bir karinedir (TMK m.598). Kesin hüküm teşkil etmez. Bu nedenle, mirasçı olduğunu sonradan anlayan veya belgede yanlışlık olduğunu iddia eden herkes, Asliye Hukuk Mahkemesinde (veya belgeyi veren kuruma karşı) 'Mirasçılık Belgesinin İptali Davası' açarak belgeyi her zaman iptal ettirebilir.", key_points: ["Mirasçılık belgesi (Veraset İlamı)", "Kesin hüküm sayılmaması", "Karine", "İptal davası"], topics: ["Mirasın Geçmesi", "Mirasçılık Belgesi"] },
    { course: "miras_hukuku", title: "Miras Hukuku - İvazlı Mirastan Feragat Sözleşmesi", difficulty: "zor", scenario: "Mirasbırakan sağlığında, yasal mirasçısı olan kızı (K) ile noterde resmi şekilde 'Miras payına karşılık 500.000 TL alması ve mirastan tamamen vazgeçmesi' konulu İvazlı Mirastan Feragat Sözleşmesi yapar. (K) parayı alır. (K)'nın altsoyu (kendi çocukları), dedeleri vefat ettiğinde (K)'nın payını isteyebilir mi?", ideal_solution: "TMK m.528 uyarınca mirasbırakan ile mirasçı arasında yapılan mirastan feragat sözleşmesi geçerlidir ve feragat eden mirasçılık sıfatını kaybeder. TMK m.528/3'e göre; 'İvazlı (karşılıklı, paralı) feragat, SÖZLEŞMEDE AKSİ KARARLAŞTIRILMAMIŞSA feragat edenin altsoyuna da etkili olur'. Olayda (K) ivaz (para) almış ve aksi kararlaştırılmamıştır. Dolayısıyla (K)'nın çocukları da (altsoyu) dedelerinin mirasından pay ALAMAZLAR.", key_points: ["Mirastan feragat sözleşmesi (TMK m.528)", "İvazlı feragat", "Altsoya etki kuralı"], topics: ["Ölüme Bağlı Tasarruflar", "Mirastan Feragat Sözleşmesi"] },
    { course: "miras_hukuku", title: "Miras Hukuku - El Yazılı Vasiyetname Şartları", difficulty: "orta", scenario: "Mirasbırakan bilgisayarda yazıp, çıktısını alıp altını tükenmez kalemle kendi eliyle imzaladığı ve yine kendi eliyle tarih (01.01.2024) attığı bir vasiyetname bırakır. Geçerli midir?", ideal_solution: "TMK m.538'e göre el yazılı vasiyetnamenin geçerli olabilmesi için yapıldığı yıl, ay ve gün gösterilerek BAŞTAN SONA KADAR mirasbırakanın EL YAZISIYLA yazılmış ve imzalanmış olması ZORUNLUDUR. Bilgisayar, daktilo vb. ile yazılıp sadece imzalanan belge el yazılı vasiyetname olarak GEÇERSİZDİR (Kesin hükümsüzlük/Butlan).", key_points: ["El yazılı vasiyetname (TMK m.538)", "Baştan sona el yazısı şartı", "Geçersizlik (Butlan)"], topics: ["Ölüme Bağlı Tasarruflar", "Vasiyetname Şekilleri"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Artmirasçı Atanması", difficulty: "zor", scenario: "Mirasbırakan, vasiyetnamesinde: 'Malvarlığımı yeğenim Ön-Mirasçı (Ö)'ye bırakıyorum. Ancak (Ö) vefat ettiğinde, bu mallar diğer yeğenim Art-Mirasçı (A)'ya intikal edecektir' der. (Ö), malları satabilir mi?", ideal_solution: "TMK m.521 uyarınca 'Artmirasçı Atanması (Fevkalade İkame)' geçerli bir ölüme bağlı tasarruftur. Bu durumda önmirasçı (Ö), mirası geçici olarak kazanır. Ancak mirası olduğu gibi (bozmadan ve satmadan) artmirasçıya devretme yükümlülüğü altındadır. Bu nedenle (Ö)'nün mülkiyeti GÜVENCELİ MÜLKİYET niteliğindedir. Tereke mallarını kural olarak SATAMAZ. Satış yapabilmesi için artmirasçının veya hakimin izni (veya teminat verilmesi) gerekir.", key_points: ["Artmirasçı (TMK m.521)", "Önmirasçı", "Güvenceli mülkiyet", "Tasarruf kısıtlaması"], topics: ["Ölüme Bağlı Tasarruflar", "Artmirasçı Atanması"] },
    { course: "miras_hukuku", title: "Miras Hukuku - Ölüm Karinesi ve Birlikte Ölüm", difficulty: "kolay", scenario: "Baba ve oğul aynı trafik kazasında vefat etmiş, ancak hangisinin önce öldüğü tıbben tespit edilememiştir. Birbirlerine mirasçı olabilirler mi?", ideal_solution: "TMK m.29 uyarınca (Birlikte Ölüm Karinesi); birden fazla kişiden hangisinin önce öldüğü ispat edilemezse, hepsi AYNI ANDA ölmüş sayılırlar. Aynı anda ölmüş sayılan kişiler BİRBİRLERİNE MİRASÇI OLAMAZLAR. Baba ve oğulun mirasları tamamen kendi yasal mirasçılarına (kendi yönlerinden ayrı ayrı) geçer.", key_points: ["Birlikte ölüm karinesi (TMK m.29)", "Aynı anda ölüm", "Mirasçı olamama durumu"], topics: ["Mirasın Açılması", "Ölüm Karinesi"] }
  ]
};

for (let course in cases) {
  appendCases(`${course}.json`, cases[course]);
}

console.log('Appended AUHF Bulk 2 Cases to data successfully.');
